### ISSUE TITLE
Можно сократить

### ISSUE THREAD

**Issue by sergoio0704** [Dirson21/PizzeriaWeb#3]
https://github.com/Dirson21/PizzeriaWeb/blob/f19d76cbfc323bcfdaa2ed7cbe4d7bd1e4fdc50b/PizzeriaWeb/Repositories/CustomerAccountRepository.cs#L53
Т.к. выбираем все колонки, можно сократить до такого вида
SELECT * FROM [CustomerAccount] WHERE [Id] = @id

**Comment by Dirson21** [comment]
Исправил
