### ISSUE TITLE
login вводит в заблуждение

### ISSUE THREAD

**Issue by sergoio0704** [Dirson21/PizzeriaWeb#4]
https://github.com/Dirson21/PizzeriaWeb/blob/f19d76cbfc323bcfdaa2ed7cbe4d7bd1e4fdc50b/PizzeriaWeb/Controllers/CustomerAccountController.cs#L49

полный url будет выглядеть http://localhost:8080/api/CustomerAccount/login/qwer@mail.ru
Как будто бы мы пытаемся залогиниться.

Можете почитать про атрибут [FromUri]
И сформировать запрос следующим образом
http://localhost:8080/api/CustomerAccount/search?email=qwer@mail.ru

Обычно подобные запросы используются исключительно в отчетах, или поисковых окнах, и чаще всего, поиск производится по нескольким критериям.
Атрибут [FromUri] позволяет получить объект из параметров запроса
https://docs.microsoft.com/en-us/aspnet/web-api/overview/formats-and-model-binding/parameter-binding-in-aspnet-web-api

**Comment by Dirson21** [comment]
Сделал с помощью [FromQuery]
