### ISSUE TITLE
Можно лишний раз не лезть в базу

### ISSUE THREAD

**Issue by sergoio0704** [Dirson21/PizzeriaWeb#5]
https://github.com/Dirson21/PizzeriaWeb/blob/f19d76cbfc323bcfdaa2ed7cbe4d7bd1e4fdc50b/PizzeriaWeb/Services/CustomerAccountService.cs#L49

Можно проверить login функцией IsNullOrEmpty у класса String, и если ответ = true, то выбросить exception.
Таким образом, сократим лишние запросы к базе

**Comment by Dirson21** [comment]
Добавил проверку
